- name: Configure SSH
  hosts: server
  become: true

  tasks:
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow SSH (Port 22)
      ufw:
        rule: allow
        port: '22'
        protocol: tcp

    - name: Allow Custom SSH (Port 2222)
      ufw:
        rule: allow
        port: '2222'
        protocol: tcp

    - name: Allow HTTP (Port 80)
      ufw:
        rule: allow
        port: '80'
        protocol: tcp

    - name: Allow HTTOS (Port 443)
      ufw:
        rule: allow
        port: '443'
        protocol: tcp

    - name: Enable UFW
      ufw:
        state: enabled
